### ISSUE TITLE
feature request: typescript support

### ISSUE THREAD

**Issue by zaoqi** [khalyomede/aegean#1]

**Comment by khalyomede** [comment]
Hi @zaoqi, good first PR thank you. I will let you know once it is completed.

**Comment by khalyomede** [comment]
Typescript extension is now supported. 

Be careful, the full **Typescript syntax** is not supported yet. 

The explaination is that if I want to support Typescript syntax, I will need to make an opniniated choice and use babel to transpile Typescript into Javascript, to be then understable by babylon (which I use to parse files). Some may find this useful, others might find this obstrusive. For the moment the second choice fits me well because it means less dependencies to manage. 

Closing this PR for now, if this is a need, please reopen this issue :)
